name: bdcallingit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_phosphor_icons: ^0.0.1+6
  fluttertoast: ^8.2.4
  get: 4.6.5
  get_storage: ^2.1.1
  http: null
  image_picker: ^1.0.4
  path: ^1.8.3
  permission_handler: ^11.0.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
